### ISSUE TITLE
psutil: AttributeError: 'module' object has no attribute '_exceptions'

### ISSUE THREAD

**Issue by bzamecnik** [rossumai/nvgpu#1]
```
Traceback (most recent call last):
  File "/usr/local/bin/nvl", line 11, in <module>
    sys.exit(pretty_list_gpus())
  File "/usr/local/lib/python2.7/dist-packages/nvgpu/list_gpus.py", line 67, in pretty_list_gpus
    df = device_table()
  File "/usr/local/lib/python2.7/dist-packages/nvgpu/list_gpus.py", line 60, in device_table
    rows = [device_status(device_index) for device_index in range(device_count)]
  File "/usr/local/lib/python2.7/dist-packages/nvgpu/list_gpus.py", line 33, in device_status
    except psutil._exceptions.NoSuchProcess:
AttributeError: 'module' object has no attribute '_exceptions'
```

**Comment by bzamecnik** [comment]
should be: `psutil.NoSuchProcess`

**Comment by bzamecnik** [comment]
Fixed
