### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by spdavern** [rossumai/nvgpu#29]
In the last month or so, new installations of nvgpu have been resulting `nvl` being non-functional. Instead of giving the expected results showing gpu utilization, I've been getting this error:
```
Traceback (most recent call last):
  File "/home/{userid}/.conda/envs/my_conda_env/bin/nvl", line 8, in <module>
    sys.exit(pretty_list_gpus())
  File "/home/{userid}/.conda/envs/my_conda_env/lib/python3.9/site-packages/nvgpu/list_gpus.py", line 107, in pretty_list_gpus
    rows = device_statuses()
  File "/home/{userid}/.conda/envs/my_conda_env/lib/python3.9/site-packages/nvgpu/list_gpus.py", line 67, in device_statuses
    return [device_status(device_index) for device_index in range(device_count)]
  File "/home/{userid}/.conda/envs/my_conda_env/lib/python3.9/site-packages/nvgpu/list_gpus.py", line 67, in <listcomp>
    return [device_status(device_index) for device_index in range(device_count)]
  File "/home/{userid}/.conda/envs/my_conda_env/lib/python3.9/site-packages/nvgpu/list_gpus.py", line 18, in device_status
    device_name = device_name.decode('UTF-8')
AttributeError: 'str' object has no attribute 'decode'
```
I found that pip uninstalling pynvml, which would uninstalls v11.5.0 and `pip install pynvml==11.4.1` restores functionality.  So, one solution might be to adding <= 11.5.0 to the pynvml install_requires in setup.py line 19.  I didn't actually test that. I am instead `conda install -c conda-forge pynvml==11.4.1` into my conda environment before I `pip install nvgpu`.

I am running nvgpu using python v3.9.16 on a Linux server running cuda v11.4 drivers.

**Comment by spdavern** [comment]
Henning Redestig's [PR](https://github.com/rossumai/nvgpu/pull/28) is a better solution than what I've offered above.

**Comment by bzamecnik** [comment]
Fixed in https://github.com/rossumai/nvgpu/pull/28.
